/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03.view;

/**
 *
 * @author Lívia Martins Bastos
 */
public class CalculadoraGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName());

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnoNascimento = new javax.swing.JLabel();
        txtAnoNascimento = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULADORA DE IDADE");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAnoNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAnoNascimento.setText("ANO DE NASCIMENTO:");
        getContentPane().add(lblAnoNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 160, 30));

        txtAnoNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtAnoNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 50, 20));

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/imagens/calculadora.png"))); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 140, 30));

        lblResultado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblResultado.setText("IDADE:");
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 200, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CALCULADORA DE IDADE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 234, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/imagens/homem.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -10, 120, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // 1. Assessor (Getter): pego o texto do campo entrada (txtAnoNascimento)
        // O metodo .getText() me permite acessar o valor que o usuário digitou.
        String anoTexto = txtAnoNascimento.getText();
        
        try {
            // Tenta converter o texto do ano para um numero  inteiro para poder calcular  
            int anoNascimento = Integer.parseInt(anoTexto);
            int ANO_ATUAL = 2025; //Definindo o ano atual para calcuo 
            
            // Faço o calculo da idade(Ano Atual - Ano de Nascimento).
            int idade = ANO_ATUAL - anoNascimento;
            
            // 2. Mutador (Setter): Exibo o resultado final da tela no rotulo.
            // Uso o metodo .setText() para mudar o texto do rótulo lblResultado
            lblResultado.setText("Idade " + idade);
            
        } catch (NumberFormatException ex){
            // Se o usuario não digitar um numero valido, mostra uma mensagem de erro no rotulo de resultado
            lblResultado.setText("Erro: Digite um ano válido");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtAnoNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoNascimentoActionPerformed
        
    }//GEN-LAST:event_txtAnoNascimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAnoNascimento;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtAnoNascimento;
    // End of variables declaration//GEN-END:variables
}
