/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.genio;

/**
 *
 * @author Lívia Martins Bastos
 */
public class telaGenio extends javax.swing.JFrame {
    
    //variavel para guardar o número secreto
    private int valorSorteado; 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaGenio.class.getName());
    
    /**
     * Creates new form telaGenio
     */
    //inicializa a tela e sorteia o valor
    public telaGenio() {
        initComponents();
        sortearValor(); //chama o sorteio ao iniciar 
        // mensagem inicial para orientar o usuario
        lblMensagem.setText("<html>Vou pensar em um valor entre 1 e 5. Tente adivinhar.</html>");
    }
    
    // metodo que usa Math.random() para gerar o numero secreto.
    private void sortearValor(){
        //gera um numero inteiro de 1 a 5
        // Math.random() gera[0.0,1.0). Multiplicando por 5, trunca (0 a 4), e soma 1(1 a 5)
        valorSorteado = (int)(Math.random() * 5) + 1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensagem = new javax.swing.JLabel();
        txtPalpite = new javax.swing.JTextField();
        btnPalpite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMensagem.setText("Vou pensar em um valor entre 1 e 5. Tente adivinhar.");
        getContentPane().add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, 30));

        txtPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(txtPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 71, -1));

        btnPalpite.setText("PALPITE");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // TODO add your handling code here:
        
        try {
            //pega o texto do campo e converte para numero (palpite do usuario)
            int palpite = Integer.parseInt(txtPalpite.getText());
            
            //validacao simples do palpite 
            if(palpite < 1 || palpite > 5) {
                lblMensagem.setText("O palpite deve ser entre 1 e 5.");
                return;
            }
            
            //logica principal
            if (palpite == valorSorteado){
                //Acertou
                lblMensagem.setText("ACERTOU!");
                btnPalpite.setEnabled(false); //desabilita o botao apos o acerto
                
            } else{
                //errou!!
                //exibe o numero sorteado conforme a imagem do dasafio 
                lblMensagem.setText("<html>ERROU! Eu pensei no valor **" + valorSorteado + "**</html>");
                btnPalpite.setEnabled(false);
            }
        } catch (NumberFormatException e){
            // mensagem de erro se o usuario digitar letras ou deixaar o campo vazio.
            lblMensagem.setText("Digite um numero, por favor.");
            
        }
     
    }//GEN-LAST:event_btnPalpiteActionPerformed

    private void txtPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPalpiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaGenio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JTextField txtPalpite;
    // End of variables declaration//GEN-END:variables
}
